version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: |
            # Customize this step if you have tests. Otherwise, remove it.
            echo "No tests found"
      - run:
          name: Build Docker image
          command: |
            docker build -t flask-hello-app .
      # Optional: Log in and push to Docker Hub
      # - run:
      #     name: Push Docker image to Docker Hub
      #     command: |
      #       echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #       docker tag flask-hello-app $DOCKERHUB_USERNAME/flask-hello-app:latest
      #       docker push $DOCKERHUB_USERNAME/flask-hello-app:latest

workflows:
  build_and_test:
    jobs:
      - build

