version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12   # CircleCI maintained Python image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/flask-hello-app:$CIRCLE_SHA1 .
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Run Docker container and test
          command: |
            docker run -d -p 5000:5000 --name flask-test $DOCKERHUB_USERNAME/flask-hello-app:$CIRCLE_SHA1
            sleep 5
            # You can add real health checks below. Example:
            curl --fail http://localhost:5000/ || (docker logs flask-test && exit 1)
            docker stop flask-test

  push:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Docker login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USERNAME/flask-hello-app:$CIRCLE_SHA1

workflows:
  version: 2
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
